### ISSUE TITLE
sip 183 session progress no audio

### ISSUE THREAD

**Issue by xbipin** [gmaruzz/saraphone#11]
most of my upstream gateways send a 183 session progress and send media of custom ringtone which FS passes onto saraphone but the media doesnt start unless the connected is signalled, anyway to get around this in FS or the dialer?

**Comment by gmaruzz** [comment]
No, early media is impossible with this release.
What I do is: FS immediately answer the call from SaraPhone, and pass it any early media from leg B, before bridging.
You can have a look at dialplan entries into "resources" directory

**Comment by xbipin** [comment]
i just noticed this uses a sip.js library thats from 2017, would it be possible to use the latest one?

ok i can also switch to same behavior in FS dialplan but is there any way in FS we can detect this is a wss call and only then answer the call before bridging?
