### ISSUE TITLE
Unable to load webphone - Stuck at "Please Wait" in chrome

### ISSUE THREAD

**Issue by rabbani2611** [gmaruzz/saraphone#12]
Hi Giovanni,

I have downloaded SaraPhone and tried to load up in Chrome and it appears to be stuck at "Please wait" Any clue as to why this issue?

We would like to test your webrtc for our pbx platform based on 2600hz kazoo. Let us know if that is supported.

Thanks
Rabbani

![image](https://user-images.githubusercontent.com/20176023/79758606-f3e21300-8360-11ea-8166-db0158b6fdaf.png)

**Comment by gmaruzz** [comment]
There is nothing in 2600hz kazoo that makes obstacle to SaraPhone

BUT you must configure Kazoo to listen for wss and answer webrtc etc

when you have Kazoo listening and answering webrtc, set the proxy, the port and the domain(s) in saraphone.html

so, you may want to see a tutorial on how to configure Kamailio (Kazoo frontend) to manage webrtc
ALSO
you may need rtpengine to translate between DTLS-SRTP and RTP

if your company need commercial consulting, feel free to contact me

**Comment by rabbani2611** [comment]
Thanks for your prompt response.

Yes, I have enabled WebSockets and configured Kamailio to listen 

Do we need to preset the login and password as well?

Regarding consulting, I will you if we need any customization but prior to that, we would like to have an easy way to demo it

**Comment by gmaruzz** [comment]
please be sure you cloned the entire project, and you give permission to web server to serve it all... the saraphone.html needs to download saraphone.js and all related stuff, eg, all various subdirectories...
check in javascript console what goes wrong

**Comment by gmaruzz** [comment]
let me kow if your problem with non loading goes away, I will close this tomorrow...
waiting from your news.

**Comment by summitrabz** [comment]
Thanks again for reopening the case.

Yes, I have cloned the entire project and provided the necessary permissions.

My setup is a standalone VM with:
- Debian 9
- NGINX

Objective: I'm trying installing and configuring for this scenario:
VM1: WSS SIP Server (Kamailio) listening on port 5065 (TLS & UDP) and WS SIP Server (Kamailio) listening on Port 5064 (TCS & UDP)  

```
tcp    LISTEN     0      128    1.2.3.4:5064                  *:*                   users:(("kamailio",pid=21186,fd=56))
udp    LISTEN     0      128    1.2.3.4:5064                  *:*                   users:(("kamailio",pid=21186,fd=56))
udp    LISTEN     0      128    1.2.3.4:5065                  *:*                   users:(("kamailio",pid=21186,fd=56))
```
VM 2: Web Server ( Nginx) + SaraPhone

Are there any other prerequisites or dependency that need to be installed in a fresh installation and do we need to have public SSL certification installed prior to having this installed?

Here are the permissions
```
root@v16:/var/www/html# git clone https://github.com/gmaruzz/saraphone.git;
root@v16:/var/www/html# chown -R www-data:www-data saraphone;
root@v16:/var/www/html# ls -la
drwxr-xr-x 10 www-data www-data 4096 Apr 21 11:52 saraphone
root@v16:/var/www/html/saraphone# ls -la
total 288
drwxr-xr-x 10 www-data www-data  4096 Apr 21 11:52 .
drwxr-xr-x  5 root     root      4096 Apr 21 10:11 ..
-rw-r--r--  1 www-data www-data  3338 Apr 21 09:01 app_config.php
-rw-r--r--  1 www-data www-data   861 Apr 21 09:01 app_defaults.php
-rw-r--r--  1 www-data www-data  4776 Apr 21 09:01 app_languages.php
-rw-r--r--  1 www-data www-data  1505 Apr 21 09:01 app_menu.php
-rw-r--r--  1 www-data www-data    13 Apr 21 09:01 CNAME
-rw-r--r--  1 www-data www-data   389 Apr 21 09:01 _config.yml
-rw-r--r--  1 www-data www-data 15057 Apr 21 09:01 contacts.php
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 css
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 doc
-rw-r--r--  1 www-data www-data  1150 Apr 21 09:01 favicon.ico
drwxr-xr-x  8 www-data www-data  4096 Apr 21 09:01 .git
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 img
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 js
-rw-r--r--  1 www-data www-data 16725 Apr 21 09:01 LICENSE
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 mp3
-rw-r--r--  1 www-data www-data  2245 Apr 21 09:01 patch.diff
-rw-r--r--  1 www-data www-data   577 Apr 21 09:01 patch.README
-rw-r--r--  1 www-data www-data  5968 Apr 21 09:01 README.md
drwxr-xr-x  3 www-data www-data  4096 Apr 21 09:01 resources
-rw-r--r--  1 www-data www-data  1998 Apr 21 09:01 root.php
-rw-r--r--  1 www-data www-data 51193 Apr 21 09:07 saraphone.html
-rw-r--r--  1 www-data www-data 30882 Apr 21 09:01 saraphone.js
-rw-r--r--  1 www-data www-data  5999 Apr 21 09:01 saraphone.lua
-rw-r--r--  1 www-data www-data 68558 Apr 21 09:01 saraphone.php
drwxr-xr-x  2 www-data www-data  4096 Apr 21 09:01 wav

```

I have tired in Chrom and Firefox in **Window 10** and both of them showing the issue.

Any other clue to assist in overcoming this hurdle?

**Comment by gmaruzz** [comment]
yes, as written in README.md, you **need** public valid SSL certs, for both HTTPS and WSS

also, you **need** to access it from the public internet, using the Full qualified domain

I would suggest, reformat the machine with nginx, install fusionpbx+saraphone EXACTLY as described, and have it work.
When it works with its own FusionPBX, **and only at that time**, just change proxy address and port to point to kamailio.

use the debug console of browser to see what's wrong
