### ISSUE TITLE
Call to undefined method database

### ISSUE THREAD

**Issue by girishdharmaraj1980** [gmaruzz/saraphone#13]
Sir,
I am using Fusionpbx on Centos7 and mariadb for the database.  When I login to saraphone under Apps I am getting the below error. Is this something to do with database connection ?

Fatal error: Call to undefined method database::select() in /var/www/html/app/saraphone/saraphone.php on line 57

**Comment by gmaruzz** [comment]
seems so :)
this has only be tested with standard install on debian9, as per 
https://github.com/gmaruzz/saraphone/blob/master/doc/INSTALL.txt

please contribute patches or pull requests to make it work on CentOS too, if you installed from standard install script.

Btw, How you installed FusionPBX? Maybe is just a too old version.
SaraPhone works with LATEST install, eg. git master FusionPBX

You may want to bring your install to latest FusionPBX, and retest Saraphone...

Let us know how it goes...

**Comment by girishdharmaraj1980** [comment]
Using the latest fusionpbx release, but I am not using Postgresql but Maraidb. Perhaps that could be the reason I suppose.

**Comment by gmaruzz** [comment]
I repeat the question:
are you using the install script? How you use it?
I have no problem in spinning a centos VM, please, just tell me exactly what to do at that point.

Eg: I have ssh access to a new centos machine (which centos version?)
then?

please let us know
