### ISSUE TITLE
Do not register and back to login

### ISSUE THREAD

**Issue by shaun-swann** [gmaruzz/saraphone#14]
I am trying to work with Asterisk (not FusionPBX) and when I click Login a black screen flashes then goes back to the login screen. I have configured the User, Password, Name, SIP Domain, Wss Proxy, Port. Details work using another webRTC dialer (sipml5).
Wondering if you can provide any guidance on what I maybe missing?
Many thanks :)

**Comment by gmaruzz** [comment]
Hello!
Activate the javascript debug console in browser, and look at what happens.
Is probably: 
1) wrong proxy address or domain
2) certs are not accepted

Let us know

**Comment by shaun-swann** [comment]
> Hello!
> Activate the javascript debug console in browser, and look at what happens.
> Is probably:
> 
> 1. wrong proxy address or domain
> 2. certs are not accepted
> 
> Let us know

Thank you - I ended up entering the complete uri into saraphone.ja line 877 as per a previous comment from juha-h and this seemed to make it work now. I am now looking at the BLF fields to get them underway as well.

**Comment by gmaruzz** [comment]
please, let us know how it goes, do we can update the wiki
Thank you!
