### ISSUE TITLE
Error when loading Saraphone: Cannot use object of type database as array

### ISSUE THREAD

**Issue by ggflow** [gmaruzz/saraphone#15]
I have followed the installation instructions and getting the error below when loading the saraphone application (that's all I see nothing else loads except for that error).

My system has the following installed:

FusionPBX 4.4.11
Freeswitch 1.8.6
PHP 7.1.33

`Fatal error: Uncaught Error: Cannot use object of type database as array in /var/www/fusionpbx/app/saraphone/saraphone.php:77 Stack trace: #0 {main} thrown in /var/www/fusionpbx/app/saraphone/saraphone.php on line 77`

**Comment by gmaruzz** [comment]
Fusion 4.4 is not supported
please use latest, from installer (eg, git master)
eg, 4.5
