### ISSUE TITLE
no display name on incoming calls throws exception?

### ISSUE THREAD

**Issue by davehorton** [gmaruzz/saraphone#16]
First of all, great work Giovanni !! Many thanks for a very useful tool.

I noticed that this line assumes all incoming calls will have a display name in the From header:

https://github.com/gmaruzz/saraphone/blob/eed9dd9617b6ba401f862f9ce1a89944f1b8a97c/saraphone.js#L416

When I sent this INVITE for an incoming call (which I believe is valid) I saw the app throw an exception:

```
020-04-30 20:25:40.652968 send 1220 bytes to wss/[xxx]:48492 at 20:25:40.652872:
INVITE sip:7jmfc9sb@cob9elv8j9h3.invalid;transport=wss SIP/2.0^M
Via: SIP/2.0/WSS xxx.xxx.xxx:4433;branch=z9hG4bKS3XBSj9gBaX6g^M
Max-Forwards: 70^M
From: <sip:0015083082809@xxx.xxx.xxx:48492>;tag=KD1r1Xa3t7e1F^M
To: <sip:daveh@x.x.x.x:48492>^M
Call-ID: 99dd1694-05c3-1239-27a8-06241ca032e2^M
CSeq: 19585378 INVITE^M
Contact: <sip:172.31.32.10:4433;transport=wss>^M
Content-Type: application/sdp^M
Content-Length: 757^M
X-CID: 998db3d8-05c3-1239-be86-000000000000^M
```

**Comment by gmaruzz** [comment]
thank you very much!!
and does it crashes, or just print exception in javascript console?
