### ISSUE TITLE
Multiple Profiles Support in FusionPBX

### ISSUE THREAD

**Issue by LogicalNZ** [gmaruzz/saraphone#17]
I have followed your instructions but the phone cannot login. I think the issue has something to do with Multiple internal SIP profiles?

What should I do?

**Comment by gmaruzz** [comment]
You must edit both your SIP Profiles AND your Domains:
================
SIP Profiles:
menu->Advanced->Sip Profiles
for each "internal" Sip Profile:
wss-binding :74XX True
#note the colon in the port value, sao is colon then portnumber, XX is a number
================

DOMAINS:
menu->advanced->domains
click on a domainname
for each domainname
go at bottom right of page
click on Add (domain setting)

Category: saraphone
Subcategory: wss_port
Type: text
Value: the port number (no colon) you assigned to the profile of this domain
Enabled: True
================
