### ISSUE TITLE
488: Incompatible SDP 

### ISSUE THREAD

**Issue by LogicalNZ** [gmaruzz/saraphone#18]
Tried to demo to a customer and got the above error in the soft-phone. What causes this?

**Comment by gmaruzz** [comment]
do you really think this is a bug report?
at least please try to do your job collecting info... 
full javascript console log
what dialplan
freeswitch console debug
etc etc etc
(also, how do you demoed? wehy don't you test before demo to customer? :D )
maybe you tested not in public internet? (eg, an ICE problem?)
you really do not give any info...

**Comment by LogicalNZ** [comment]
I have no idea how to collect that data, if there is a problem with the product and not working - then is that not a bug?

Maybe you need a support forum?

Sent from my iPad

On 4/05/2020, at 5:35 PM, gmaruzz <notifications@github.com> wrote:

﻿

do you really think this is a bug report?
at least please try to do your job collecting info...
full javascript console log
what dialplan
freeswitch console debug
etc etc etc
(also, how do you demoed? wehy don't you test before demo to customer? :D )
maybe you tested not in public internet? (eg, an ICE problem?)
you really do not give any info...

**Comment by gmaruzz** [comment]
I am sorry Logical, probably is not the time for you to use this "product", maybe  you want to come back in some months, when other people with more technical knowledge will have reported problems with enough info to have them fixed
I would bet in your case is an ICE problem generated by network problems, and/or firewall, but you probably can't do much with this hint.
So, I suggest you come back in some months, and sorry it has not worked for you
