### ISSUE TITLE
Cross Domain Ext

### ISSUE THREAD

**Issue by mtghr** [gmaruzz/saraphone#19]
Hi

 i just installed the phone and i set up a user that maps to Ext 103 and i have a yealink deivce assigned 

when i log in to the saraphone it it will pull in the drop down all 103 from all domains 

![saraphone](https://user-images.githubusercontent.com/34816536/81225365-1c038000-8fb7-11ea-9ce2-7548748d9df3.png)

**Comment by gmaruzz** [comment]
thank you very much for reporting!
I will look into it

**Comment by gmaruzz** [comment]
fixed with commit 06c6460

**Comment by gmaruzz** [comment]
@mtghr you may want to "git pull" and retest, thanks again for reporting

**Comment by mtghr** [comment]
thank you i will test later and report back
