### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by ghenry** [gmaruzz/saraphone#2]
Excellent work!!!

Will you have something like this?

https://github.com/librestack/librecast/blob/master/CONTRIBUTING.md

**Comment by gmaruzz** [comment]
Ciao Gavin Henry!
Nothing so elaborated, at this moment!
You just do one pull request for each one change you want.
That's it :))
Eg: the smallest the change in the pull request, the better.
Obviously, you can make many small changes, in many pull requests...
Thank you for asking! <3
-giovanni
