### ISSUE TITLE
login page keeps loading

### ISSUE THREAD

**Issue by mtghr** [gmaruzz/saraphone#20]
in test it in my domain and it worked fine 

i gave it to one customer to test and by him the login page will keep trying to login and reload 

i checked in the page code it has the right 
username
password
domain name
pot number

i tired it in chrome and explorer 

any idea what to test

**Comment by gmaruzz** [comment]
What exactly you do?
What means "I gave to a customer"?
What changes btw you and customer?
Do customer have firewall blocking wss port?
If you can use it, anyone in world can use it in same condition
So, what changed?
Have you checked the javascript console?
The domain is the same?
The proxy is the same?
I suspect two things:
1) firewall
2) he changed the proxy name and there is no certificate for new proxy
Anyway, please check the javascript console
I will wait two days for complete info, then I will close this issue

**Comment by mtghr** [comment]
ok to be clear i meant test server vs production server

i am noticing that WEBRTC was never really set up on that server i will configure it now

**Comment by gmaruzz** [comment]
@mtghr 
Oks, please update your SaraPhone with git pull
I just added code to alert about misconfiguration and network problems
5 minutes ago :)

**Comment by mtghr** [comment]
Sure

**Comment by mtghr** [comment]
Dataphone Stretch
    
    

    
    
        table {
            border-spacing: 0;
            border-collapse: collapse;
            width: 100%;
        }

        td {
            padding: 0;
        }

        p {
            font-size: 16px;
        }

        img {
            border: 0;
        }

        .content {
            line-height: 26px;
            font-size: 15px;
        }

        .bluelink {
            text-decoration: none;
            color: #140D39 !important;
        }

        span.Object {
            color: inherit !important;
        }

        span.Object-hover {
            color: inherit !important;
            text-decoration: none !important;
        }

        u+.body .gmail-blend-screen {
            background: #000;
            mix-blend-mode: screen;
        }

        u+.body .gmail-blend-difference {
            background: #000;
            mix-blend-mode: difference;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
            line-height: 100%;
        }

        a[x-apple-data-detectors=true] {
            color: inherit !important;
            text-decoration: inherit !important;
        }

        @media screen and (max-width: 599.98px) {


            .column-wrapper .padding {
                padding-right: 0 !important;
                padding-left: 0 !important;
            }

            .column-wrapper {
                padding: 0 30px !important;
            }

        }

        @media screen and (max-width: 499.98px) {
            .column-wrapper {
                padding: 0 20px !important;
            }
        }

        @media screen and (max-width: 399.98px) {
            .column-wrapper {
                padding: 0 10px !important;
            }
        }


        :root {
            color-scheme: light dark;
            supported-color-schemes: light dark;
        }

        @media (prefers-color-scheme: dark) {

            body,
            table,
            .darkmode-bg {
                background: #FEFEFE !important;
                color: #140D39 !important;
            }

            [data-ogsc] body,
            table,
            .darkmode-bg {
                background: #FEFEFE !important;
                color: #140D39 !important;
            }

            .darkmode-transparent {
                background-color: transparent !important;
            }

            [data-ogsc] .darkmode-transparent {
                background-color: transparent !important;
            }

        }

         
        @import ***@***.***,400..800;1,400..800&display=swap');
    
    





    
        

            
            
                                
                ‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏
            
            

            

            


                
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                            
                                
                                    
                                        Get your Business up to

                                        
                                            
                                        
                                        Speed.
                                    
                                
                            
                        
                        
                            
                                
                                    
                                        Line by Line.
                                    
                                
                            
                            
                                
      
                                        
                                    

                                
                            
                            
                                
                                
                            
                        
                    
                
                

                
                
                    
                        
                            
                                
                                    
                                        
                                        
                                            
                                                                         
                                                          

        
        
        Hi Reply+Aijueggmod47zmiz7bw33en4yaflnevbnhhcjfeoxq,

        We hope you're doing great.

        We want to remind you that the carriers have made 10DLC registration mandatory for businesses sending SMS messages. Starting October 31, 2024, any unregistered numbers could face message blocking, meaning your messages may not reach your customers.

        To better understand what this means and why it's important, you can check out our blog posts:
        
            What Happens When Carriers Block Unregistered 10DLC Numbers?
            10DLC Registration: Why It’s Important for Your Business SMS
        

        If you haven’t completed your 10DLC registration yet, please reach out to our support team at ***@***.***, and they will guide you through the process to avoid disruptions.

        Let us know if you have any questions.

           


                                                                                      
                                                        
                                                    
                                                



                                                

                                            
                                        
                            
                        
                    
                
            
            
            
            

            
            
                
                    
                        
                            
                                
                                    
                                
                            
                        
                        
                            
                                
                                  
                                   
                                     
                                               Unsubscribe
                                                                        
                                    |
                                    
                                        Privacy Policy
                                    
                                    |
                                    
                                        Contact Us
                                    
                                
                            
                        
                    
                
            

            
                
                    
                        
                            
                                
                                    © 2024 Dataphone, Inc.
                                
                                
                                    All rights reserved.
                                
                                
                                    1449 37th St, 612B, Brooklyn, New York 11218, US
                                
                            

                        
                    
                
            

            
                
                    
                        
                            
                                
                                    Follow us on
