### ISSUE TITLE
Hold, XTrans, etc. buttons did not work during call

### ISSUE THREAD

**Issue by rbetancor** [gmaruzz/saraphone#21]
I see the DTMF codes on the FS CLI, but they do not do anything.

I saw that the .lua script have some calls to bind_digit_action ... but I don't saw that lua script been executed during the call stablishement or the SaraPhone loading.

Maybe some missing instruction on the install docs?

**Comment by gmaruzz** [comment]
you MUST follow the README
eg, menu->advanced->upgrade->app defaults
ETC

**Comment by gmaruzz** [comment]
![Selection_107](https://user-images.githubusercontent.com/331862/81534408-48791c80-9368-11ea-94eb-8bdcd5b8e318.jpg)

**Comment by gmaruzz** [comment]
![Selection_108](https://user-images.githubusercontent.com/331862/81534618-a443a580-9368-11ea-9d9f-fcf81a687962.jpg)

**Comment by gmaruzz** [comment]
![Selection_109](https://user-images.githubusercontent.com/331862/81534626-a9085980-9368-11ea-8c44-b68e22c0b7fd.jpg)

**Comment by rbetancor** [comment]
Sorry I didn't mention it, but I follow all the steps, not fully restarting the FS was the issue, thanks
