### ISSUE TITLE
Voicemail Bug

### ISSUE THREAD

**Issue by mtghr** [gmaruzz/saraphone#25]
Good Morning

i had an issue with my fusionpbx that when a user called in to listen to VM free-switch was playing back  for adavnced options press 5, this was before the greeting that said you have x new voicemails...... we noticed in the CLI that as soon as the voicemail gets activated  the sara dialplan got invoked, so i just disabled all the dialplans from sara and my VM works regular now

**Comment by gmaruzz** [comment]
please attach a complete debug level output from freeswitch console...

**Comment by gmaruzz** [comment]
feel free to reopen with relevant info
