### ISSUE TITLE
Inbound Call - No Audio (except for firefox)

### ISSUE THREAD

**Issue by ggflow** [gmaruzz/saraphone#26]
Outbound everything works fine in all my tested browsers.

Inbound calls ie. extension 100 (yealink handset) calls 200 (Saraphone). 
Saraphone 200 can hear the audio from Yealink 100
Yealink 100 can NOT hear audio from Saraphone 200.

This is an issue on Google Chrome (latest version), Opera (latest version), Microsoft Edge.

Tested on Windows and Mac. Same thing.

However with Firefox, all works perfectly.

**Comment by gmaruzz** [comment]
maybe you have more than one microphone?

have you tried on a different computer?

**Comment by gmaruzz** [comment]
please attach the entire output of the javascript console (ctrl+i)

**Comment by gmaruzz** [comment]
( just tested with chrome Version 83.0.4103.61 (Official Build) (64-bit), works both ways )

**Comment by ggflow** [comment]
Here is the output from Chrome (not working)

Inbound call from 3000 (Yealink Phone) to 3003 (Saraphone)

No audio from 3000 to 3003.

[](https://pastebin.com/msw2YST2)

**Comment by gmaruzz** [comment]
you seems to use an older version... ( userAgentString: "SIP.js/0.7.8 SaraPhone 01" )

can you please reinstall it all, follow all steps described, and retest?

please remember to do the 
Menu->Advanced->Upgrade, check:

    App Defaults
    Menu Defaults
    Permission Defaults

etc etc

all steps must be repeated

If problem persists, open a new issue
