### ISSUE TITLE
Remember Registration Information

### ISSUE THREAD

**Issue by seven1240** [gmaruzz/saraphone#34]
Hi Giovanni,

I installed to https://xswitch.cn/sara/ it looks great, however, I don't use fusionpbx and it seems it cannot remember the account info I filled. Each time I refresh it goes back to the default.

I'd like to ask is that a missing feature or would you like to add it, I generally remember it in localStorage, see the verto based demo: https://git.xswitch.cn/xswitch/xcc-examples/src/branch/master/webrtc/es6/demo.js

Would you like to add it or accept a PR?

Cheers,
Seven.

**Comment by gmaruzz** [comment]
What a pleasure reading from you, Seven!!

Actually in future I want to release a much evolved version of it

In the mean time, yes, please, send a PR

(when I'll release the new version, for sure I will integrate your PR too)

Say hello from me to your wife, to BinBin and to all the friends!

-giovanni

**Comment by seven1240** [comment]
Here you go: https://github.com/gmaruzz/saraphone/pull/35

I can now use it as a front-end ONLY phone without PHP.

Great to know there will be a new version. I'd like to see it works w/o PHP or any other back-ends in the future if possible. Actually, it's ok to implement some back-end APIs if it's more useful, just make that as an advanced feature, I can even add those kind of APIs in XSwitch :)

My wife and BinBin are very happy heard from you. Say hello to Sara too. I Say hello to Sara every time I make a call on Saraphone :). 

Cheers,
Seven.
