### ISSUE TITLE
FusionPBX 5.1 PHP8 Saraphone Not Work

### ISSUE THREAD

**Issue by leandrodes** [gmaruzz/saraphone#38]
I iam try use saraphone in my fusionpbx 5.1 and not work, when i try use in my older instance the fusionpbx 4.X its work.

Now i tested in other instance that use FusionPBX 5.1 but use PHP 7.4 and its OK, i try new installations in Debian 12 that use PHP 8.1 by default and not work, its possible any change to work with PHP 8 in Saraphone?

When i try use saraphone with PHP 8 i receive only screen to select device but not is possivel select or change any configuration.

**Comment by ardavanhashemzadeh** [comment]
replacing every occurrence of '_mac_' with '_' in saraphone.php fixed it for me (its not a php issue, the database column name change is what broke it).

**Comment by ardavanhashemzadeh** [comment]
Here's the patch, tested working on FusionPBX 5.2: https://github.com/gmaruzz/saraphone/pull/39

**Comment by sjacobflaherty** [comment]
@gmaruzz can you please add @ardavanhashemzadeh's commit? Issue is documented, easily reproducible, and breaks functionality when not fixed.

**Comment by gmaruzz** [comment]
merged fix

**Comment by gmaruzz** [comment]
merged fix
