### ISSUE TITLE
Failed opening required 'resources/require.php'

### ISSUE THREAD

**Issue by juha-h** [gmaruzz/saraphone#4]
I tried saraphone according to "How to Install SaraPhone on WSS SIP Server + Web Server" and got this:
```
[Sat Apr 18 13:58:19.697412 2020] [php7:warn] [pid 22243] [client 192.168.43.82:37986] PHP Warning:  require_once(resources/require.php): failed to open stream: No such file or directory in /var/www/saraphone/contacts.php on line 30, referer: https://test.tutpro.com/saraphone/saraphone.html
[Sat Apr 18 13:58:19.697469 2020] [php7:error] [pid 22243] [client 192.168.43.82:37986] PHP Fatal error:  require_once(): Failed opening required 'resources/require.php' (include_path='.:/usr/share/php:/var/www') in /var/www/saraphone/contacts.php on line 30, referer: https://test.tutpro.com/saraphone/saraphone.html
```
Such a file (require.php) does not exist.

**Comment by gmaruzz** [comment]
quoting from the section of the README you read:

You can then access SaraPhone at:

https://your.webserver.address/saraphone/saraphone.html

(note the ending: HTML not PHP)

**Comment by gmaruzz** [comment]
yep, contacts section has to be deleted from html

**Comment by juha-h** [comment]
Could you do that or make it conditional depending on if FusionPBX exists?

**Comment by gmaruzz** [comment]
I am just simply commenting out that :))

**Comment by gmaruzz** [comment]
commit 7cdb0b2710b21292019e7581ab875e66294f6f87
