### ISSUE TITLE
Bugs and feature improvements

### ISSUE THREAD

**Issue by xbipin** [gmaruzz/saraphone#6]
i noticed there is a FS patch which is based on old code so doesnt apply to master, secondly if you enter a incorrect login it doesnt indicate if its incorrect, thirdly would it be possible to add code to activate proximity sensor and activate the earpiece rather than speakerphone on a mobile.

I tried the dialer with my FS server using wss and that works fine provided DTLS isnt blocked in a country but for some odd reason i start getting choppy audio after a while and then it totally stops whereas SRTP works flawless with the same FS instance along with TLS. i tried the opentokrtc demo and it works flawless which also runs on webrtc so no idea whats causing the choppy audio

**Comment by xbipin** [comment]
even though after applying the patch to FS manually the show registration command on FS shows some weird contact

**Comment by gmaruzz** [comment]
please open one issue for each, well, issue :)) I close this one, please reopen as many as needed
