### ISSUE TITLE
FEATURE REQUEST: SDES

### ISSUE THREAD

**Issue by xbipin** [gmaruzz/saraphone#9]
the calls work fine with FS over wss after patch applied manually but i noticed when dialing from certain countries where DTLS should work and isnt being blocked based on tests using the opentokrtc demo, i still get choppy audio after a minute into the call and then no audio at all. I believe jssip library supports SDES so would it be possible to add an option to use that on SRTP as the works flawless

**Comment by gmaruzz** [comment]
this is based on sip.js
it uses standard DTLS webrtc 
I am not aware of possibility of changing this
pull requests gladly accepted
